#server.port=8888
#
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/basketball?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=root
#
#mybatis.mapper-locations=classpath:mappers/*.xml
#mybatis.type-aliases-package=zhanweikai.com.pojo



server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basketball?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: zhanweikai.com.pojo